---
# tasks file for archlinux/oh-my-zsh

- name: "[OH MY ZSH] install zsh"
  pacman:
    name: zsh

- name: "[OH MY ZSH] setting up zsh as default shell for Vagrant user"
  user:
    name: vagrant
    shell: /bin/zsh

- name: "[OH MY ZSH] check if oh-my-zsh has been already downloaded"
  stat:
    path: /home/vagrant/.oh-my-zsh
  register: stat_result

- include: "oh-my-zsh.yml"
  when: stat_result.stat.exists == False
